// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://pavjnepxzpucmehoidey.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdmpuZXB4enB1Y21laG9pZGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNjE4NDMsImV4cCI6MjA0ODczNzg0M30.AXI8Aa9he-Bsj1zCKD0c6DrLGRyQimQdDO9_1fuamQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);